object Form1: TForm1
  Left = 200
  Top = 192
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'Form1'
  ClientHeight = 625
  ClientWidth = 872
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  PixelsPerInch = 96
  TextHeight = 13
  object LP: TPanel
    Left = 24
    Top = 20
    Width = 800
    Height = 600
    Color = 2169560
    TabOrder = 0
    object LP_B2: TShape
      Left = 8
      Top = 8
      Width = 785
      Height = 585
      Brush.Color = 2169560
      Pen.Color = clWhite
      Pen.Width = 5
    end
    object LP_B1: TShape
      Left = 560
      Top = 20
      Width = 220
      Height = 477
    end
    object LP_Name: TLabel
      Left = 584
      Top = 28
      Width = 69
      Height = 20
      Cursor = crHandPoint
      Caption = 'LP_Name'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 20
      Font.Name = 'Bauhaus 93'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_Logo: TImage
      Left = 585
      Top = 48
      Width = 170
      Height = 170
      Transparent = True
    end
    object LP_Hall: TLabel
      Left = 596
      Top = 218
      Width = 56
      Height = 20
      Cursor = crHandPoint
      Caption = 'LP_Hall'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 20
      Font.Name = 'Bauhaus 93'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_iHall: TImage
      Left = 585
      Top = 240
      Width = 170
      Height = 170
    end
    object LP_lCapacity: TLabel
      Left = 593
      Top = 420
      Width = 126
      Height = 15
      Cursor = crHandPoint
      Caption = 'Kapacita . . . . . .'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 15
      Font.Name = 'Bolt Bd BT'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_Capacity: TLabel
      Left = 728
      Top = 420
      Width = 33
      Height = 15
      Cursor = crHandPoint
      Caption = 'Cap.'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 15
      Font.Name = 'Bolt Bd BT'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_B3: TShape
      Left = 24
      Top = 20
      Width = 528
      Height = 560
    end
    object LP_B4: TShape
      Left = 30
      Top = 26
      Width = 515
      Height = 25
      Brush.Color = 2169560
      Pen.Style = psClear
      Pen.Width = 0
    end
    object LP_P_L: TLabel
      Left = 40
      Top = 26
      Width = 12
      Height = 20
      Cursor = crHandPoint
      Caption = 'P:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = LP_P_LClick
    end
    object LP_C_L: TLabel
      Left = 62
      Top = 26
      Width = 13
      Height = 20
      Cursor = crHandPoint
      Caption = 'C:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = LP_C_LClick
    end
    object LP_J_L: TLabel
      Left = 84
      Top = 26
      Width = 106
      Height = 20
      Cursor = crHandPoint
      Caption = 'Jmeno, Prijmeni:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = LP_J_LClick
    end
    object LP_V_L: TLabel
      Left = 244
      Top = 26
      Width = 28
      Height = 20
      Cursor = crHandPoint
      Caption = 'Vek:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = LP_V_LClick
    end
    object LP_F_L: TLabel
      Left = 280
      Top = 26
      Width = 18
      Height = 20
      Cursor = crHandPoint
      Caption = 'FS:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = LP_F_LClick
    end
    object LP_T_L: TLabel
      Left = 310
      Top = 26
      Width = 19
      Height = 20
      Cursor = crHandPoint
      Caption = 'TS:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = LP_T_LClick
    end
    object LP_Z_L: TLabel
      Left = 340
      Top = 26
      Width = 19
      Height = 20
      Cursor = crHandPoint
      Caption = 'ZS:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = LP_Z_LClick
    end
    object LP_L_L: TLabel
      Left = 370
      Top = 26
      Width = 11
      Height = 20
      Cursor = crHandPoint
      Caption = 'L:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = LP_L_LClick
    end
    object LP_Al_L: TLabel
      Left = 442
      Top = 26
      Width = 17
      Height = 20
      Cursor = crHandPoint
      Caption = 'Al:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_Zp_L: TLabel
      Left = 470
      Top = 26
      Width = 20
      Height = 20
      Cursor = crHandPoint
      Caption = 'Zp:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_Gp_L: TLabel
      Left = 495
      Top = 26
      Width = 22
      Height = 20
      Cursor = crHandPoint
      Caption = 'Gp:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_Ap_L: TLabel
      Left = 518
      Top = 26
      Width = 21
      Height = 20
      Cursor = crHandPoint
      Caption = 'Ap:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_Zl_L: TLabel
      Left = 395
      Top = 26
      Width = 16
      Height = 20
      Cursor = crHandPoint
      Caption = 'Zl:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_Gl_L: TLabel
      Left = 417
      Top = 26
      Width = 18
      Height = 20
      Cursor = crHandPoint
      Caption = 'Gl:'
      Color = 2169560
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = 20
      Font.Name = 'Calibri'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object LP_C_M: TMemo
      Left = 56
      Top = 50
      Width = 25
      Height = 527
      Alignment = taRightJustify
      BevelInner = bvNone
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      HideSelection = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
    end
    object LP_V_M: TMemo
      Left = 245
      Top = 50
      Width = 25
      Height = 527
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 2
    end
    object LP_P_M: TMemo
      Left = 39
      Top = 50
      Width = 18
      Height = 527
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 6
    end
    object button1: TButton
      Left = 712
      Top = 528
      Width = 75
      Height = 25
      Caption = 'Konec'
      TabOrder = 7
      OnClick = Button1Click
    end
    object LP_J_M: TMemo
      Left = 80
      Top = 50
      Width = 165
      Height = 527
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
    end
    object LP_F_M: TMemo
      Left = 276
      Top = 50
      Width = 25
      Height = 527
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 3
    end
    object LP_T_M: TMemo
      Left = 306
      Top = 50
      Width = 25
      Height = 527
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 4
    end
    object LP_Z_M: TMemo
      Left = 336
      Top = 50
      Width = 25
      Height = 527
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 5
    end
    object LP_L_M: TMemo
      Left = 366
      Top = 50
      Width = 25
      Height = 527
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      OEMConvert = True
      ParentFont = False
      ReadOnly = True
      TabOrder = 8
    end
    object LP_Zl_M: TMemo
      Left = 389
      Top = 50
      Width = 25
      Height = 527
      Alignment = taRightJustify
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 9
    end
    object LP_Gl_M: TMemo
      Left = 411
      Top = 50
      Width = 25
      Height = 527
      Alignment = taRightJustify
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 10
    end
    object LP_Al_M: TMemo
      Left = 436
      Top = 50
      Width = 25
      Height = 527
      Alignment = taRightJustify
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 11
    end
    object LP_Zp_M: TMemo
      Left = 464
      Top = 50
      Width = 25
      Height = 527
      Alignment = taRightJustify
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 12
    end
    object LP_Gp_M: TMemo
      Left = 489
      Top = 50
      Width = 25
      Height = 527
      Alignment = taRightJustify
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 13
    end
    object LP_Ap_M: TMemo
      Left = 512
      Top = 50
      Width = 25
      Height = 527
      Alignment = taRightJustify
      BevelInner = bvSpace
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 2169560
      Font.Height = 18
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 14
    end
  end
end
